version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: certifi
    versions:
    - 2.6.0
  - dependency-name: ex_doc
    versions:
    - 0.24.0
