language: elixir

sudo: false

elixir:
  - 1.10.3

otp_release:
  - '22.3'
  - '23.0'

cache:
  directories:
    - _build
    - deps
    - priv/plts

env: MIX_ENV=test

script:
  - mix coveralls.travis
  - mix credo
  - mix format --check-formatted
  - mix dialyzer
